### ISSUE TITLE
Installation in VS2019 fails

### ISSUE THREAD

**Issue by Khaos66** [swdotcom/visualstudio-codetime#1]
I've already created an issue in the old repo here: [#46](https://github.com/swdotcom/swdc-visualstudio/issues/46)
But I think the issue is better hosted in this repo.

I think that [this line](https://github.com/swdotcom/visualstudio-codetime/blob/a71d8469b6c2d00ba1a169a16a233c38c193c966/CodeTime/source.extension.vsixmanifest#L26) causes the issue
As in [this line](https://github.com/swdotcom/visualstudio-codetime/blob/a71d8469b6c2d00ba1a169a16a233c38c193c966/CodeTime/source.extension.vsixmanifest#L15) you need to allow old versions of the CodeEditor. Like this:
```XML
<Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[14.0,18.0)" DisplayName="Visual Studio core editor" />
```

**Comment by xavluiz** [comment]
Hi @Khaos66,

Thank you for posting that information. I'll add that today. Sorry for the delay.

**Comment by xavluiz** [comment]
v2.6.8 should now be available in the marketplace with a prerequisite version range of 14.0 - 18.0. Let us know if this solves the issue, thanks!

**Comment by Khaos66** [comment]
Yes I guess that fixes the issue. Thanks
